# Generated by Django 3.2 on 2021-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname_u', models.CharField(max_length=200)),
                ('lname_u', models.CharField(max_length=200)),
                ('emial_u', models.EmailField(max_length=254)),
                ('mobile_u', models.ImageField(max_length=10, upload_to='')),
            ],
        ),
    ]
