# Generated by Django 3.2 on 2021-04-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add_person',
            new_name='Uploader',
        ),
    ]
