# Generated by Django 3.2 on 2021-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_add_person_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploader',
            old_name='emial_u',
            new_name='email_u',
        ),
        migrations.AlterField(
            model_name='uploader',
            name='mobile_u',
            field=models.IntegerField(),
        ),
    ]
