# Generated by Django 3.2 on 2021-04-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210413_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploader',
            name='image_l',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
