# Generated by Django 3.0.4 on 2021-04-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_uploader_image_l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploader',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
