# Generated by Django 3.0.4 on 2021-04-15 18:21

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210415_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=website.models.rename),
        ),
    ]
